import React, { useState, useEffect } from 'react';
import { Sparkles, MessageSquare, Brain, CheckCircle, TrendingUp } from 'lucide-react';
import { MOCK_LLM_INSIGHTS } from '../utils/pathwayMockData';

const LLMInsightsPanel = () => {
  const [insights, setInsights] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [isDemoMode, setIsDemoMode] = useState(false);

  useEffect(() => {
    const fetchInsights = async () => {
      try {
        const response = await fetch('http://localhost:8000/insights/llm');
        if (!response.ok) throw new Error('Failed to fetch LLM insights');
        const data = await response.json();
        setInsights(data);
        setIsDemoMode(false);
        setError(null);
      } catch (err) {
        setInsights(MOCK_LLM_INSIGHTS);
        setIsDemoMode(true);
        setError(null);
      } finally {
        setLoading(false);
      }
    };

    fetchInsights();
    const interval = setInterval(fetchInsights, 5000); // Update every 5 seconds

    return () => clearInterval(interval);
  }, []);

  if (loading) {
    return (
      <div className="bg-gradient-to-br from-purple-900/30 to-pink-900/30 rounded-lg p-6 border border-purple-500/30">
        <div className="flex items-center space-x-2 mb-4">
          <Brain className="w-6 h-6 text-purple-400 animate-pulse" />
          <h3 className="text-xl font-bold text-purple-400">AI Financial Advisor</h3>
        </div>
        <p className="text-gray-400">Generating insights...</p>
      </div>
    );
  }

  return (
    <div className="bg-gradient-to-br from-purple-900/30 to-pink-900/30 rounded-lg p-6 border border-purple-500/30">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center space-x-3">
          <Brain className="w-6 h-6 text-purple-400" />
          <h3 className="text-xl font-bold text-purple-400">AI Financial Advisor</h3>
          <span className="px-2 py-1 bg-pink-500/20 rounded text-xs text-pink-300">
            LLM-Powered
          </span>
        </div>

        {/* Confidence Indicator */}
        <div className="flex items-center space-x-2 bg-purple-500/20 px-3 py-1 rounded">
          <Sparkles className="w-4 h-4 text-yellow-400" />
          <span className="text-xs text-purple-300">
            {((insights?.confidence || 0) * 100).toFixed(0)}% confident
          </span>
        </div>
      </div>

      <div className="space-y-6">
        {/* Financial Summary */}
        <div className="p-4 bg-gray-800/50 rounded-lg border border-purple-500/20">
          <div className="flex items-start space-x-3">
            <MessageSquare className="w-5 h-5 text-purple-400 mt-1 flex-shrink-0" />
            <div>
              <h4 className="text-sm font-semibold text-purple-300 mb-2">
                Financial Status Summary
              </h4>
              <p className="text-gray-300 leading-relaxed">
                {insights.summary}
              </p>
            </div>
          </div>
        </div>

        {/* Risk Explanation */}
        <div className="p-4 bg-gray-800/50 rounded-lg border border-blue-500/20">
          <div className="flex items-start space-x-3">
            <CheckCircle className="w-5 h-5 text-blue-400 mt-1 flex-shrink-0" />
            <div>
              <h4 className="text-sm font-semibold text-blue-300 mb-2">
                Risk Analysis
              </h4>
              <p className="text-gray-300 leading-relaxed">
                {insights.risk_explanation}
              </p>
            </div>
          </div>
        </div>

        {/* AI Recommendations */}
        {insights.recommendations && insights.recommendations.length > 0 && (
          <div className="p-4 bg-gray-800/50 rounded-lg border border-green-500/20">
            <div className="flex items-start space-x-3 mb-3">
              <TrendingUp className="w-5 h-5 text-green-400 mt-1 flex-shrink-0" />
              <h4 className="text-sm font-semibold text-green-300">
                Personalized Recommendations
              </h4>
            </div>
            <ul className="space-y-2 ml-8">
              {insights.recommendations.map((rec, index) => (
                <li key={index} className="text-gray-300 text-sm flex items-start">
                  <span className="text-green-400 mr-2">•</span>
                  <span>{rec}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Metadata */}
        <div className="flex items-center justify-between text-xs text-gray-500">
          <span>Generated by Pathway xPack + LLM</span>
          <span>
            {insights?.generated_at ? new Date(insights.generated_at).toLocaleTimeString() : 'Just now'}
          </span>
        </div>
      </div>

      {/* AI Badge */}
      <div className="mt-4 pt-4 border-t border-purple-500/20">
        <div className="flex items-center justify-center space-x-2">
          <Sparkles className="w-4 h-4 text-yellow-400" />
          <span className="text-xs text-gray-400">
            Powered by real-time streaming analytics & natural language processing
          </span>
        </div>
      </div>
    </div>
  );
};

export default LLMInsightsPanel;
